### ISSUE TITLE
Error on close channel

### ISSUE THREAD

**Issue by alekomcev** [epam/java-cme-mdp3-handler#71]
### When close method of MdpChannel is invoked the exception below is happen
java.nio.channels.ClosedSelectorException
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:83)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
	at com.epam.cme.mdp3.core.channel.MdpFeedWorker.select(MdpFeedWorker.java:167)
	at com.epam.cme.mdp3.core.channel.MdpFeedWorker.run(MdpFeedWorker.java:149)
	at java.lang.Thread.run(Thread.java:748)

**Comment by swarwick** [comment]
Do you have a reproducible case for this? I have yet to see this in any system we have been running.

**Comment by iamolever** [comment]
I suppose it's possible if we did not start FeedWorker, but we are closing it

**Comment by iamolever** [comment]
Accidentally pushed in master... But fix is just one row. Please review it, maybe rollback is not required

**Comment by iamolever** [comment]
@alekomcev , did you test this branch?
